#!/bin/tcsh

#SBATCH --job-name="evaluate_by_grid_cell"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --array=1-10
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_grid_cell_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/mcd_experiment01_td-to-ts"

set CENTRAL_LOSS_WEIGHTS=("01.0" "02.0" "03.0" "04.0" "05.0" "06.0" "07.0" "08.0" "09.0" "10.0")
set central_loss_weight=${CENTRAL_LOSS_WEIGHTS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/central-loss-weight=${central_loss_weight}"
set prediction_dir_name="${model_dir_name}/validation_sans_uq"

set GRID_ROWS=("000" "001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012")
set GRID_COLUMNS=("000" "001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012" "013" "014" "015" "016" "017" "018" "019" "020" "021" "022" "023" "024" "025" "026" "027" "028" "029" "030" "031" "032" "033" "034" "035" "036")

set i=1

while ($i <= ${#GRID_ROWS})
    set j=1

    while ($j <= ${#GRID_COLUMNS})
        set this_input_file_name="${prediction_dir_name}/grid-row=${GRID_ROWS[$i]}/predictions_grid-row=${GRID_ROWS[$i]}_grid-column=${GRID_COLUMNS[$j]}.nc"
        
        if (-e "$this_input_file_name") then
            set this_output_file_name="${prediction_dir_name}/all_lead_times/grid-row=${GRID_ROWS[$i]}/evaluation_grid-row=${GRID_ROWS[$i]}_grid-column=${GRID_COLUMNS[$j]}.nc"

            python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
            --input_prediction_file_name="${this_input_file_name}" \
            --event_freq_in_training=0.50886938 \
            --num_prob_thresholds=1001 \
            --num_reliability_bins=20 \
            --num_bootstrap_reps=1 \
            --output_eval_file_name="${this_output_file_name}"
        endif
    
        @ j = $j + 1
    end
    
    @ i = $i + 1
end
