#!/bin/tcsh

#SBATCH --job-name="evaluate_by_month"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --array=1-3
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_month_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/experiment13"

set LAG_TIME_COUNTS=(21 3 2)
set SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS=("fractions-smallrad" "largerad-smallrad" "none")
set USE_DATA_AUG_FLAGS=(1 1 1)

set lag_time_count=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set lag_time_count=`printf "%02d" $lag_time_count`
set ships_lagged_predictor_group_string=${SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS[$SLURM_ARRAY_TASK_ID]}
set use_data_aug_flag=${USE_DATA_AUG_FLAGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-lag-times=${lag_time_count}_lagged-ships-predictors=${ships_lagged_predictor_group_string}_data-aug=${use_data_aug_flag}"
set prediction_dir_name="${model_dir_name}/validation_2005-2009"

set MONTHS=("01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12")
set i=1

while ($i <= ${#MONTHS})
    set this_input_file_name="${prediction_dir_name}/predictions_month=${MONTHS[$i]}.nc"
    
    if (-e "$this_input_file_name") then
        set this_output_file_name="${prediction_dir_name}/evaluation_month=${MONTHS[$i]}.nc"

        python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
        --input_prediction_file_name="${this_input_file_name}" \
        --event_freq_in_training=0.07267640234 \
        --num_prob_thresholds=1001 \
        --num_reliability_bins=20 \
        --num_bootstrap_reps=1 \
        --output_eval_file_name="${this_output_file_name}"
    endif
    
    @ i = $i + 1
end
