#!/bin/tcsh

#SBATCH --job-name="eval_by_basin_validation"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --array=1
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=eval_by_basin_validation_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/experiment07_reduced_preds"

set DENSE_LAYER_DROPOUT_RATES=(0.4)
set CONV_LAYER_L2_WEIGHTS=(0.001)
set DENSE_LAYER_COUNTS=(3)

set dense_layer_dropout_rate=${DENSE_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set conv_layer_l2_weight=${CONV_LAYER_L2_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
set dense_layer_count=${DENSE_LAYER_COUNTS[$SLURM_ARRAY_TASK_ID]}

set dense_layer_dropout_rate_string=`printf "%.1f" $dense_layer_dropout_rate`
set conv_layer_l2_weight_string=`printf "%.12f" $conv_layer_l2_weight`
set dense_layer_count_string=`printf "%1d" $dense_layer_count`

set model_dir_name="${TOP_MODEL_DIR_NAME}/dense-layer-dropout-rate=${dense_layer_dropout_rate_string}_conv-layer-l2-weight=${conv_layer_l2_weight_string}_dense-layer-count=${dense_layer_count_string}"
set prediction_dir_name="${model_dir_name}/validation_2005-2009"

set BASIN_ID_STRINGS=("AL" "SL" "EP" "CP" "WP" "IO" "SH")
set i=1

while ($i <= ${#BASIN_ID_STRINGS})
    set this_input_file_name="${prediction_dir_name}/predictions_basin-id-string=${BASIN_ID_STRINGS[$i]}.nc"
    
    if (-e "$this_input_file_name") then
        set this_output_file_name="${prediction_dir_name}/evaluation_basin-id-string=${BASIN_ID_STRINGS[$i]}.nc"

        python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
        --input_prediction_file_name="${this_input_file_name}" \
        --event_freq_in_training=0.07267640234 \
        --num_prob_thresholds=1001 \
        --num_reliability_bins=20 \
        --num_bootstrap_reps=1 \
        --output_eval_file_name="${this_output_file_name}"
    endif
    
    @ i = $i + 1
end
