#!/bin/tcsh

#SBATCH --job-name="plot_predictors_2014AL08_real_time"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --array=2
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_predictors_2014AL08_real_time_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_project/learning_examples/with_real_time_ships/rotated_with_storm_motion/imputed/normalized"
set NORMALIZATION_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_project/learning_examples/rotated_with_storm_motion/normalization_params_1993-2004_2015-2019.nc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/crps_experiment02_predictor_types"

set FOURTH_LAST_LAYER_DROPOUT_RATES=("0.700" "0.300" "0.500" "0.100" "0.100")
set THIRD_LAST_LAYER_DROPOUT_RATES=("0.700" "0.300" "0.500" "0.500" "0.500")
set SECOND_LAST_LAYER_DROPOUT_RATES=("0.500" "0.900" "0.100" "0.300" "0.300")
set SATELLITE_LAG_TIME_COUNTS=("3" "1" "3" "3" "1")
set SHIPS_FORECAST_PREDICTOR_COUNTS=("65" "65" "65" "00" "00")
set SATELLITE_USE_TEMPORAL_DIFF_FLAGS=("0" "0" "1" "1" "0")

set fourth_last_layer_dropout_rate=${FOURTH_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set third_last_layer_dropout_rate=${THIRD_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set second_last_layer_dropout_rate=${SECOND_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set satellite_lag_time_count=${SATELLITE_LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set ships_forecast_predictor_count=${SHIPS_FORECAST_PREDICTOR_COUNTS[$SLURM_ARRAY_TASK_ID]}
set satellite_use_temporal_diff_flag=${SATELLITE_USE_TEMPORAL_DIFF_FLAGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/dropout-rates=${fourth_last_layer_dropout_rate}-${third_last_layer_dropout_rate}-${second_last_layer_dropout_rate}_num-satellite-lag-times=${satellite_lag_time_count}_num-ships-forecast-predictors=${ships_forecast_predictor_count}_satellite-use-temporal_diffs=${satellite_use_temporal_diff_flag}"
set model_metafile_name="${model_dir_name}/model_metadata.p"

python3 -u "${CODE_DIR_NAME}/plot_predictors.py" \
--input_model_metafile_name="${model_metafile_name}" \
--input_norm_example_file_name="${EXAMPLE_DIR_NAME}/learning_examples_2014AL08.nc" \
--input_normalization_file_name="${NORMALIZATION_FILE_NAME}" \
--input_prediction_file_name="${model_dir_name}/testing_on_real_time_ships/predictions.nc" \
--first_init_time_string="2010-01-01-000000" \
--last_init_time_string="2011-01-01-000000" \
--plot_time_diffs_if_used=1 \
--output_dir_name="${model_dir_name}/testing_on_real_time_ships/predictor_plots_2014AL08"
