#!/bin/tcsh

#SBATCH --job-name="evaluate_by_grid_cell"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00
#SBATCH --array=1-48
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_grid_cell_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/experiment13"

# set LAG_TIME_COUNTS=(2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21 2 2 3 3 21 21)
# set SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS=("none" "none" "none" "none" "none" "none" "fractions" "fractions" "fractions" "fractions" "fractions" "fractions" "largerad" "largerad" "largerad" "largerad" "largerad" "largerad" "smallrad" "smallrad" "smallrad" "smallrad" "smallrad" "smallrad" "fractions-largerad" "fractions-largerad" "fractions-largerad" "fractions-largerad" "fractions-largerad" "fractions-largerad" "fractions-smallrad" "fractions-smallrad" "fractions-smallrad" "fractions-smallrad" "fractions-smallrad" "fractions-smallrad" "largerad-smallrad" "largerad-smallrad" "largerad-smallrad" "largerad-smallrad" "largerad-smallrad" "largerad-smallrad" "fractions-largerad-smallrad" "fractions-largerad-smallrad" "fractions-largerad-smallrad" "fractions-largerad-smallrad" "fractions-largerad-smallrad" "fractions-largerad-smallrad")
# set USE_DATA_AUG_FLAGS=(0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1)

set lag_time_count=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set lag_time_count=`printf "%02d" $lag_time_count`
set ships_lagged_predictor_group_string=${SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS[$SLURM_ARRAY_TASK_ID]}
set use_data_aug_flag=${USE_DATA_AUG_FLAGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-lag-times=${lag_time_count}_lagged-ships-predictors=${ships_lagged_predictor_group_string}_data-aug=${use_data_aug_flag}"
set prediction_dir_name="${model_dir_name}/validation_2005-2009"

set GRID_ROWS=("000" "001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012")
set GRID_COLUMNS=("000" "001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012" "013" "014" "015" "016" "017" "018" "019" "020" "021" "022" "023" "024" "025" "026" "027" "028" "029" "030" "031" "032" "033" "034" "035" "036")

set i=1

while ($i <= ${#GRID_ROWS})
    set j=1

    while ($j <= ${#GRID_COLUMNS})
        set this_input_file_name="${prediction_dir_name}/grid-row=${GRID_ROWS[$i]}/predictions_grid-row=${GRID_ROWS[$i]}_grid-column=${GRID_COLUMNS[$j]}.nc"
        
        if (-e "$this_input_file_name") then
            set this_output_file_name="${prediction_dir_name}/grid-row=${GRID_ROWS[$i]}/evaluation_grid-row=${GRID_ROWS[$i]}_grid-column=${GRID_COLUMNS[$j]}.nc"

            python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
            --input_prediction_file_name="${this_input_file_name}" \
            --event_freq_in_training=0.07267640234 \
            --num_prob_thresholds=1001 \
            --num_reliability_bins=20 \
            --num_bootstrap_reps=1 \
            --output_eval_file_name="${this_output_file_name}"
        endif
    
        @ j = $j + 1
    end
    
    @ i = $i + 1
end
