#!/bin/tcsh

#SBATCH --job-name="evaluate_by_basin"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --array=1-7
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_by_basin_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/crps_experiment02_predictor_types"

# set FOURTH_LAST_LAYER_DROPOUT_RATES=("0.700" "0.700" "0.700" "0.700" "0.900" "0.900" "0.900" "0.900" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100" "0.700" "0.700" "0.700" "0.700" "0.900" "0.900" "0.900" "0.900" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100" "0.700" "0.700" "0.700" "0.700" "0.900" "0.900" "0.900" "0.900" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100")
# set THIRD_LAST_LAYER_DROPOUT_RATES=("0.700" "0.700" "0.700" "0.700" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.100" "0.100" "0.100" "0.100" "0.500" "0.500" "0.500" "0.500" "0.700" "0.700" "0.700" "0.700" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.100" "0.100" "0.100" "0.100" "0.500" "0.500" "0.500" "0.500" "0.700" "0.700" "0.700" "0.700" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.500" "0.100" "0.100" "0.100" "0.100" "0.500" "0.500" "0.500" "0.500")
# set SECOND_LAST_LAYER_DROPOUT_RATES=("0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100" "0.900" "0.900" "0.900" "0.900" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100" "0.900" "0.900" "0.900" "0.900" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300" "0.900" "0.900" "0.900" "0.900" "0.100" "0.100" "0.100" "0.100" "0.900" "0.900" "0.900" "0.900" "0.500" "0.500" "0.500" "0.500" "0.300" "0.300" "0.300" "0.300")
# set SATELLITE_LAG_TIME_COUNTS=("1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3")
# set SHIPS_FORECAST_PREDICTOR_COUNTS=("00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65" "00" "00" "65" "65")
# set SATELLITE_USE_TEMPORAL_DIFF_FLAGS=("0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1")

set fourth_last_layer_dropout_rate=${FOURTH_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set third_last_layer_dropout_rate=${THIRD_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set second_last_layer_dropout_rate=${SECOND_LAST_LAYER_DROPOUT_RATES[$SLURM_ARRAY_TASK_ID]}
set satellite_lag_time_count=${SATELLITE_LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set ships_forecast_predictor_count=${SHIPS_FORECAST_PREDICTOR_COUNTS[$SLURM_ARRAY_TASK_ID]}
set satellite_use_temporal_diff_flag=${SATELLITE_USE_TEMPORAL_DIFF_FLAGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/dropout-rates=${fourth_last_layer_dropout_rate}-${third_last_layer_dropout_rate}-${second_last_layer_dropout_rate}_num-satellite-lag-times=${satellite_lag_time_count}_num-ships-forecast-predictors=${ships_forecast_predictor_count}_satellite-use-temporal_diffs=${satellite_use_temporal_diff_flag}"
set prediction_dir_name="${model_dir_name}/testing"

set BASIN_ID_STRINGS=("AL" "SL" "EP" "CP" "WP" "IO" "SH")
set i=1

while ($i <= ${#BASIN_ID_STRINGS})
    set this_input_file_name="${prediction_dir_name}/predictions_basin-id-string=${BASIN_ID_STRINGS[$i]}.nc"
    
    if (-e "$this_input_file_name") then
        set this_output_file_name="${prediction_dir_name}/evaluation_ignore-minor-false-alarms/evaluation_basin-id-string=${BASIN_ID_STRINGS[$i]}.nc"

        python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
        --input_prediction_file_name="${this_input_file_name}" \
        --event_freq_in_training=0.07267640234 \
        --num_prob_thresholds=1001 \
        --num_reliability_bins=20 \
        --num_bootstrap_reps=1 \
        --ignore_fa_intensity_change_thres_m_s01=12.86 \
        --output_eval_file_name="${this_output_file_name}"
    endif
    
    @ i = $i + 1
end
