#!/bin/tcsh

#SBATCH --job-name="run_forward_perm_test_katrina"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=30:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=run_forward_perm_test_katrina_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set EXAMPLE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_project/learning_examples/imputed/normalized"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/experiment02"

set DENSE_LAYER_DROPOUT_RATE=0.2
set CONV_LAYER_L2_WEIGHT=0.001
set DENSE_LAYER_COUNT=3

set dense_layer_dropout_rate_string=`printf "%.1f" $DENSE_LAYER_DROPOUT_RATE`
set conv_layer_l2_weight_string=`printf "%.12f" $CONV_LAYER_L2_WEIGHT`
set dense_layer_count_string=`printf "%1d" $DENSE_LAYER_COUNT`

set model_dir_name="${TOP_MODEL_DIR_NAME}/dense-layer-dropout-rate=${dense_layer_dropout_rate_string}_conv-layer-l2-weight=${conv_layer_l2_weight_string}_dense-layer-count=${dense_layer_count_string}"
set model_file_name="${model_dir_name}/model.h5"
set output_file_name="${model_dir_name}/xai_katrina/forward_perm_test.nc"

python3 -u "${CODE_DIR_NAME}/run_permutation.py" \
--input_model_file_name="${model_file_name}" \
--input_example_dir_name="${EXAMPLE_DIR_NAME}" \
--cyclone_id_strings "2005AL12" \
--do_backwards_test=0 \
--num_bootstrap_reps=1 \
--num_steps=10 \
--output_file_name="${output_file_name}"
