#!/bin/tcsh

#SBATCH --job-name="evaluate_models"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --array=1-2
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_models_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_standalone/ml4tc"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4tc_models/experiment13_temporal_diffs"

set LAG_TIME_COUNTS=(2 3)
set SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS=("none" "largerad-smallrad")
set USE_DATA_AUG_FLAGS=(1 1)

set lag_time_count=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
set lag_time_count=`printf "%02d" $lag_time_count`
set ships_lagged_predictor_group_string=${SHIPS_LAGGED_PREDICTOR_GROUP_STRINGS[$SLURM_ARRAY_TASK_ID]}
set use_data_aug_flag=${USE_DATA_AUG_FLAGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/num-lag-times=${lag_time_count}_lagged-ships-predictors=${ships_lagged_predictor_group_string}_data-aug=${use_data_aug_flag}"
set prediction_file_name="${model_dir_name}/validation_2005-2009/predictions.nc"
set evaluation_file_name="${model_dir_name}/validation_2005-2009/evaluation.nc"

python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
--input_prediction_file_name="${prediction_file_name}" \
--event_freq_in_training=0.07267640234 \
--num_prob_thresholds=1001 \
--num_reliability_bins=20 \
--num_bootstrap_reps=1 \
--output_eval_file_name="${evaluation_file_name}"
